project:
  type: website
  output-dir: docs

website:
  title: "CSC 210 Fall 2024"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - syllabus.qmd
      - programming-assignments.qmd
      - modules.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source

