---
title: "Academic Integrity"
---

**All work you submit for grading in this course must be your own. Submitting work that includes (minor and/or major) components that are not your own work is considered plagiarism. Instances of plagiarism will be reported to the Dean of Students.**

Keep in mind that all assignments and practice problems provided in this course are meant to help you practice the skills that you will need to do well in all assessments (including on paper quizzes and exams), so it is generally in your best interest to avoid taking shortcuts even on practice problems (which are ungraded).

Sharing your code with others (in addition to copying code from others) is considered a break of the academic integrity code (unauthorized assistance) as well. If code that you claim is yours is found in other students' submission(s), you will also be reported to the Dean of Students. 

The university keeps track of multiple offenses. For the College of Science, the second reported offense results in a failing grade for the class in which the second offense occurred.

Gradescope has a similarity tool, which compares all submissions and creates reports with submission overlaps. Similarity reports will be generated also with code generated by AI tools, and code found online.

The penalty for breaking the academic integrity code is zero points awarded to the assignment found to be plagiarizes and -5 points from final grade (out of 100 points).

