---
title: "CSC 210 Fall 2024"
---

The main goal of this course is to learn how to decompose problems and solve them with a program and do this in an effective manner that enables your future self and others to read, understand, and maintain your programs. Other goals include learning a second programming language (Java), learning decomposition and debugging strategies, and learning GUI event-driven programming (JavaFX).

* [Course D2L](https://d2l.arizona.edu/d2l/home/1497427)
* [Gradescope](https://www.gradescope.com/courses/839822)

Where to start:

* [Syllabus](syllabus.html)
* [Schedule + Materials](modules.html)

# Instructor Information

-   Adriana Picoral [🔈](https://namedrop.io/adrianapicoral "how to pronounce Adriana Picoral")

    -   Office: [Gould-Simpson](https://goo.gl/maps/h8Vyf7RNQiMAScDY6) 811

    -   Email: adrianaps\@arizona.edu

    -   Instructor Website: [adrianapicoral.com](https://adrianapicoral.com/)

    -   Office hours (open door, drop in, my office [GS](https://goo.gl/maps/h8Vyf7RNQiMAScDY6) 811):

        -   Monday 2:30pm to 3:30pm

        -   Wednesday 10:30am to 12:30pm

# TA office hours

TA office hours take place in Gould-Simpson room 821.

<iframe src="https://docs.google.com/spreadsheets/d/1pVdOEZQNaZuKvvIHYkwk4oJHWMfG5-g1QdFHNEmFHy4/pubhtml?gid=0&amp;single=true&amp;widget=true&amp;headers=false" width="100%" height="600px"></iframe>
        
# Information about the materials for this course

The materials (including slides and assignments) for this course are based on materials from previous CSC 210 instances created by other instructors, including: Michelle Strout, and Rick Mercer.