---
title: "Programming Assignments"
---

```{r}
#| eval: true
#| echo: false
#| message: false
#| warning: false
library(tidyverse)
library(readxl)
data <- read_excel("assessment-deadlines.xlsx")
```


[Fill out this survey with your GitHub username so that you can get credit for your project submissions](https://uarizona.co1.qualtrics.com/jfe/form/SV_4GyaYKWTKqYvafk).

# PA 1

* Deadline: `r data %>% filter(Assignment == "PA1") %>%  select(Deadline)` -- Wednesday, 11:30pm

* [Instructions](programming-assignment-01.html)


# PA 2

* Deadline: `r data %>% filter(Assignment == "PA2") %>%  select(Deadline)` -- Wednesday, 11:30pm

* [Instructions](programming-assignment-02.html)

# PA 3

* Deadline: `r data %>% filter(Assignment == "PA3") %>%  select(Deadline)` -- Friday, 11:30pm

* [Instructions](programming-assignment-03.html)

# PA 4

* Deadline: `r data %>% filter(Assignment == "PA4") %>%  select(Deadline)` -- Friday, 11:30pm

* [Instructions](programming-assignment-04.html)

# PA 5

* UML class diagram: `r data %>% filter(Assignment == "PA5a") %>%  select(Deadline)` -- Friday, 11:30pm
* Full implementation: `r data %>% filter(Assignment == "PA5b") %>%  select(Deadline)` -- Wednesday, 11:30pm

* [Instructions](programming-assignment-05.html)

# PA 6

* Deadline: `r data %>% filter(Assignment == "PA6") %>%  select(Deadline)` -- Wednesday, 11:30pm

* [Instructions](programming-assignment-06.html)


