---
title: "Java Objects"
format:
  revealjs:
    slide-number: c/t
    show-slide-number: all
---


## Classes

What is a class?

## Classes

* Collection of methods and attributes (information/values)
* Template, blueprint of cookie cutter to construct many objects

**Modularity**: Classes allow us to split the problem to be solved into distinct tasks

## Demonstration

We will create a class called `UseBankAccount`

Attributes: 1) ID (String), and 2) balance (double)

Methods:

* getID()
* getBalance()
* deposit(double amount)
* withdraw(double amount)

<small>*adapted from Rick Mercer's slides*</small>

## Solution

```{java}
public class BankAccount {
	
	private String ID;
	private double balance;
	
	public BankAccount(String initID, double initBalance) {
		ID = initID;
		balance = initBalance;
	}
	
	public String getID() {
		return ID;
	}
	
	public double getBalance() {
		return balance;
	}
	
	public void deposit(double amount) {
		balance = balance + amount;
	}
	
	public void withdraw(double amount) {
		balance = balance - amount;
	}

}
```


## Expand

Create a console application (another class with a public main method) that does the following:

1. create a new BankAccount for `"Casey"` (ID) with `100` for balance
1. request user keyboard input for amount to deposit
1. update account balance (deposit the amount)
1. print out a message with new balance

```{java}
BankAccount anAcct = new BankAccount("Casey", 100); 
```


## Solution

```{java}
import java.util.Scanner;

public class UseBankAccount {
	
	public static void main(String[] args) {
		
		BankAccount anAcct = new BankAccount("Casey", 100); 
		
		// Input
		System.out.print("Enter amount to deposit: ");
		Scanner keyboard = new Scanner(System.in);
		double amount = keyboard.nextDouble();
		keyboard.close();
		
		// Process
		anAcct.deposit(amount);
		
		// Output
		System.out.println("New balance: " + anAcct.getBalance());
	}
}
```

## Expand

Modify your console application to ask whether the user wants to deposit or
withdraw, and execute the desired operation

## Solution

```{java}
import java.util.Scanner;

public class UseBankAccount {
	
	public static void main(String[] args) {
		
		BankAccount anAcct = new BankAccount("Casey", 100); 
		
		// Input
		Scanner keyboard = new Scanner(System.in);
		
		System.out.print("Deposit (D) or Withdraw (W)? "); 	
		String operation = keyboard.next();
		
		
		if (operation.equals("D")) {
			System.out.print("Enter amount to deposit: ");
			double amount = keyboard.nextDouble();
			
			// Process
			anAcct.deposit(amount);
			
			// Output
			System.out.println("New balance: " + anAcct.getBalance());
		}
		
		if (operation.equals("W")) {
			System.out.print("Enter amount to withdraw: ");
			double amount = keyboard.nextDouble();
			
			// Process
			anAcct.withdraw(amount);
			
			// Output
			System.out.println("New balance: " + anAcct.getBalance());
		}
		

		System.out.println("Thank you.");
		
		keyboard.close();
		
		
	}
}
```


## Scanner

The `Scanner` class (from `java.util`) is used to get different types of input

We use `System.in` to read keyboard input:

```{java}
    Scanner myObj = new Scanner(System.in);  // Scanner object
    String userInput = myObj.nextLine();  // method to read user input
    System.out.println(userInput); 
```

For files, we need the `File` class (from `java.io`) 

```{java}
    File myFile = new File("myTextFile.txt");
    Scanner myReader = new Scanner(myFile);
```

However, we need to deal with `FileNotFoundException`

## Scanner

```{java}
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

public class FileReadExample {

	public static void main(String[] args) throws FileNotFoundException {
		File myFile = new File("myTextFile.txt");
		Scanner myReader = new Scanner(myFile);
	}

}
```


## Scanner

We use the same `Scanner` method `.nextLine()`

```{java}
String line = myReader.nextLine();
```

Task:

* Read a line in the file and and print it out
* Read all lines in a file and print each one out

## Read file line  -- solution 1

```{java}
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

public class FileReadExample {

	public static void main(String[] args) throws FileNotFoundException {
		File myFile = new File("myTextFile.txt");
		Scanner myReader = new Scanner(myFile);
		
		String line1 = myReader.nextLine();
		System.out.println(line1);
		
		String line2 = myReader.nextLine();
		System.out.println(line2);
		
		myReader.close();
	}

}
```

## Read file line  -- solution 2

```{java}
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

public class FileReadExample {

	public static void main(String[] args) throws FileNotFoundException {
		File myFile = new File("myTextFile.txt");
		Scanner myReader = new Scanner(myFile);
		
		System.out.println(myReader.nextLine());
		System.out.println(myReader.nextLine());
		
		myReader.close();
	}

}
```

## While loop

What if we didn't know how many lines there were in the file?

The method `.hasNextLine()` returns a boolean

Modify the previous solution to generalize it to any number of lines


## While loop -- solution

```{java}
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

public class FileReadExample {

	public static void main(String[] args) throws FileNotFoundException {
		File myFile = new File("myTextFile.txt");
		Scanner myReader = new Scanner(myFile);
		
		while (myReader.hasNextLine()) {
			System.out.println(myReader.nextLine());
		}
		myReader.close();
	}

}
```


## String

`String` is a class (title capitalization)

We can construct strings two ways:

```{java}
String str = new String("with new");
String str2 = "Don't need new"
```

Some string methods:

```{java}
.equals(String otherString)
.length() // len() function in python
.charAt(int index) // [] indexing in python
.substring(int beginIndex, int endIndex) // [:] indexing in python
.indexOf(String str) // .find() method in python
```

Try these methods out

## String methods -- solution

```{java}
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

public class FileReadExample {

	public static void main(String[] args) throws FileNotFoundException {
		File myFile = new File("myTextFile.txt");
		Scanner myReader = new Scanner(myFile);
		
		while (myReader.hasNextLine()) {
			String line = myReader.nextLine();
			System.out.println(line.length());
			System.out.println(line.charAt(0));
			if (line.length() > 0) System.out.println(line.substring(0, 2));
			System.out.println(line.indexOf("line"));
			
		}
		myReader.close();
	}

}
```


